languageCode = "en-us"
title = "AntMe! Dokumentation"
RelativeUrls = true
uglyurls = true
theme = "AntMe"
DefaultContentLanguage = "de"
sectionPagesMenu = "nav"
publishDir = "docs"

[languages]
  [languages.de]
    title = "AntMe! Dokumentation"
    languageName = "Deutsch"
    weight = 1
  [languages.en]
    title = "AntMe! Documentation"
    languageName = "English"
    weight = 2


[menu]
  [[menu.nav]]
    name = "Home"
    url = "/index.html"
    weight = 1